services:
  trmnl-network-devices:
    build: .
    container_name: trmnl-network-devices-scanner

    network_mode: host
    pid: host
    privileged: true

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - data:/data

volumes:
  data:
